baseURL = 'https://filmsemi.pages.dev'
languageCode = 'en-us'
title = 'Film Semi'
theme = 'adult'
enableRobotsTXT = 'true'
paginate = 18

[params]
  Description = 'Film Semi Barat, Film Semi Jepang, Film Semi China, Film Adult, Film Uncrncored, Film 18, Film Dewasa, Memek & Kontol.'
  favicon = 'https://img.icons8.com/ios/512/209cee/breast.png'
  eroboom = 'https://xxx.eroboom.pw/'
  twitter = 'Rizqy'
[markup.goldmark.renderer]
 unsafe = true
[taxonomies]
  genre = 'genre'
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "genre"
    weight = 100
  [[related.indices]]
    name = "title"
    weight = 90
  [[related.indices]]
    name = "type"
    weight = 80